name: lessons_tasks_assignment
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_cache_manager: ^3.4.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  go_router: ^14.8.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.14
  build_verify: ^3.1.0
  file: ^7.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.8.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.0
  mockito: ^5.4.5
  retrofit_generator: ^9.1.9
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
